# Generated by Django 5.1.4 on 2025-01-14 18:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('road', models.CharField(blank=True, default='', max_length=50)),
                ('jibun', models.CharField(default='', max_length=50)),
                ('detail', models.CharField(default='', max_length=50)),
                ('pnu', models.CharField(default='', max_length=30)),
                ('lndpclAr', models.CharField(default='', max_length=50)),
                ('cd', models.CharField(default='', max_length=8)),
                ('landNickName', models.CharField(default='', max_length=50)),
                ('cropsInfo', models.CharField(default='', max_length=50)),
                ('additionalPhoneNum', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
    ]
