# Generated by Django 5.1.5 on 2025-02-10 21:41

import farmer.storages
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('road', models.CharField(blank=True, default='', max_length=50)),
                ('jibun', models.CharField(default='', max_length=50)),
                ('detail', models.CharField(default='', max_length=50)),
                ('pnu', models.CharField(default='', max_length=30)),
                ('lndpclAr', models.CharField(blank=True, max_length=50, null=True)),
                ('cd', models.CharField(default='', max_length=10)),
                ('landNickName', models.CharField(default='', max_length=50)),
                ('cropsInfo', models.CharField(default='', max_length=50)),
                ('additionalPhoneNum', models.CharField(blank=True, default='', max_length=50)),
                ('min_price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FarmInfoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(storage=farmer.storages.LocalImageStorage(), upload_to='images/farminfo/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
