# Generated by Django 4.2.14 on 2025-01-13 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('road', models.CharField(blank=True, default='', max_length=50)),
                ('jibun', models.CharField(default='', max_length=50)),
                ('detail', models.CharField(default='', max_length=50)),
                ('pnu', models.CharField(default='', max_length=30)),
                ('lndpclAr', models.CharField(default='', max_length=50)),
                ('cd', models.CharField(default='', max_length=8)),
                ('landNickName', models.CharField(default='', max_length=50)),
                ('cropsInfo', models.CharField(default='', max_length=50)),
                ('additionalPhoneNum', models.CharField(blank=True, default='', max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
