# Generated by Django 5.1.5 on 2025-02-27 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farminfo',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farminfoimage',
            name='farm_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farmer.farminfo'),
        ),
    ]
