# Generated by Django 5.1.4 on 2025-01-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farmer", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farminfo",
            name="cd",
            field=models.CharField(default="", max_length=10),
        ),
    ]
