# Generated by Django 5.1.4 on 2025-01-18 03:05

import django.db.models.deletion
import farmer.storages
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmInfoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('image', models.ImageField(storage=farmer.storages.LocalImageStorage(), upload_to='images/farminfo/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('farm_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='farmer.farminfo')),
            ],
        ),
    ]
