# Generated by Django 5.1.5 on 2025-01-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farminfo',
            name='min_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
