# Generated by Django 5.1.5 on 2025-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farminfo',
            name='lndpclAr',
            field=models.CharField(max_length=50),
        ),
    ]
