# Generated by Django 5.1.4 on 2025-01-19 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0003_farminfoimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farminfoimage',
            old_name='farm_info',
            new_name='land_info',
        ),
    ]
