# Generated by Django 5.1.4 on 2025-01-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TossPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=65, unique=True)),
                ('paymentKey', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('totalAmount', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
