# Generated by Django 4.2.14 on 2025-01-14 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tosspayments',
            old_name='orderId',
            new_name='tossOrderId',
        ),
    ]
