branch-defaults:
  default:
    environment: APIDroneField-env
environment-defaults:
  APIDroneField-env:
    branch: null
    repository: null
global:
  application_name: API_DroneField
  default_ec2_keyname: dronefield_ccy
  default_platform: Python 3.12 running on 64bit Amazon Linux 2023
  default_region: ap-northeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
