# Generated by Django 5.1.5 on 2025-01-29 16:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('model_number', models.CharField(blank=True, max_length=30, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Drone',
                'verbose_name_plural': 'Drones',
            },
        ),
        migrations.CreateModel(
            name='ExterminatorLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('license_title', models.CharField(blank=True, max_length=30, null=True)),
                ('license_number', models.CharField(blank=True, max_length=30, null=True)),
                ('business_registration_type', models.CharField(blank=True, max_length=30, null=True)),
                ('worker_registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('license_image', models.URLField(blank=True, max_length=500, null=True)),
                ('business_registration_image', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Exterminator License',
                'verbose_name_plural': 'Exterminator Licenses',
            },
        ),
    ]
