# Generated by Django 5.1.4 on 2025-01-28 15:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('model_number', models.CharField(blank=True, max_length=30, null=True)),
                ('capacity', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='drones/images/', verbose_name='Drone Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drone',
                'verbose_name_plural': 'Drones',
            },
        ),
        migrations.CreateModel(
            name='ExterminatorLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('license_title', models.CharField(blank=True, max_length=30, null=True)),
                ('license_number', models.CharField(blank=True, max_length=30, null=True)),
                ('lincense_nickname', models.CharField(blank=True, max_length=30, null=True)),
                ('business_registration_type', models.CharField(blank=True, max_length=30, null=True)),
                ('worker_registration_number', models.CharField(blank=True, max_length=30, null=True)),
                ('license_image', models.ImageField(blank=True, null=True, upload_to='licenses/license_images/', verbose_name='License Image')),
                ('business_registration_image', models.ImageField(blank=True, null=True, upload_to='licenses/business_registration_images/', verbose_name='Business Registration Image')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterminator_license', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exterminator License',
                'verbose_name_plural': 'Exterminator Licenses',
            },
        ),
    ]
