# Generated by Django 5.1.4 on 2025-01-20 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exterminator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Exterminator",
                "verbose_name_plural": "Exterminators",
            },
        ),
        migrations.CreateModel(
            name="ExterminatorLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=30)),
                ("model_number", models.CharField(max_length=30)),
                ("worker_registration_number", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "Exterminator License",
                "verbose_name_plural": "Exterminator Licenses",
            },
        ),
    ]
