# Generated by Django 5.1.4 on 2025-01-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='image',
            field=models.URLField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
