# Generated by Django 5.1.4 on 2025-01-08 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exterminator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exterminator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='exterminator_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exterminator',
            name='license',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license_for_exterminator', to='exterminator.exterminatorlicense'),
        ),
    ]
