# Generated by Django 5.1.4 on 2025-01-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0002_alter_drone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
