# Generated by Django 5.1.5 on 2025-01-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='capacity',
            field=models.CharField(blank=True, null=True),
        ),
    ]
