# Generated by Django 5.1.4 on 2025-01-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exterminator", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ExterminatorLicense",
            new_name="License",
        ),
    ]
