# Generated by Django 5.1.5 on 2025-01-31 04:07

import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exterminatorlicense',
            name='lincense_holder_name',
            field=models.CharField(blank=True, default=django.db.models.query.QuerySet.get, max_length=30, null=True),
        ),
    ]
