# Generated by Django 5.1.4 on 2025-01-26 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exterminator", "0003_rename_exterminatorlicense_license"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exterminator",
            name="license",
        ),
        migrations.RemoveField(
            model_name="exterminator",
            name="user",
        ),
        migrations.CreateModel(
            name="ExterminatorLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.CharField(max_length=30)),
                ("model_number", models.CharField(max_length=30)),
                ("worker_registration_number", models.CharField(max_length=30)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exterminator_license",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exterminator License",
                "verbose_name_plural": "Exterminator Licenses",
            },
        ),
        migrations.DeleteModel(
            name="License",
        ),
        migrations.DeleteModel(
            name="Exterminator",
        ),
    ]
