# Generated by Django 5.1.5 on 2025-01-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0003_alter_drone_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='capacity',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
