# Generated by Django 5.1.5 on 2025-01-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0003_alter_drone_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exterminatorlicense',
            name='lincense_nickname',
        ),
        migrations.AlterField(
            model_name='drone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drones/images/', verbose_name='Drone Image'),
        ),
    ]
