# Generated by Django 5.1.5 on 2025-01-29 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0004_remove_exterminatorlicense_lincense_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drone',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
