# Generated by Django 5.1.4 on 2025-01-26 05:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exterminator",
            "0004_remove_exterminator_license_remove_exterminator_user_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="exterminatorlicense",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
