# Generated by Django 4.2.14 on 2025-02-01 23:11

from django.db import migrations, models
import django.db.models.query


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0004_alter_exterminatorlicense_lincense_holder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exterminatorlicense',
            name='lincense_holder_name',
            field=models.CharField(blank=True, default=django.db.models.query.QuerySet.get, max_length=30, null=True),
        ),
    ]
