# Generated by Django 5.1.4 on 2025-01-26 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exterminator", "0005_exterminatorlicense_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="exterminatorlicense",
            name="business_registration_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="licenses/business_registration_images/",
                verbose_name="Business Registration Image",
            ),
        ),
        migrations.AddField(
            model_name="exterminatorlicense",
            name="license_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="licenses/license_images/",
                verbose_name="License Image",
            ),
        ),
        migrations.AlterField(
            model_name="exterminatorlicense",
            name="license_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="exterminatorlicense",
            name="model_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="exterminatorlicense",
            name="worker_registration_number",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
