# Generated by Django 5.1.5 on 2025-01-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0005_alter_drone_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exterminatorlicense',
            name='business_registration_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exterminatorlicense',
            name='license_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
