# Generated by Django 5.1.4 on 2025-01-26 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "exterminator",
            "0006_exterminatorlicense_business_registration_image_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="exterminatorlicense",
            name="owner",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exterminator_license",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
