# Generated by Django 5.1.4 on 2025-01-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "exterminator",
            "0008_rename_model_number_exterminatorlicense_lincense_nickname_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="drone",
            old_name="name",
            new_name="nickname",
        ),
    ]
