# Generated by Django 5.1.4 on 2025-01-26 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exterminator", "0009_rename_name_drone_nickname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="exterminatorlicense",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exterminator_license",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
