# Generated by Django 5.1.4 on 2025-01-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0010_alter_exterminatorlicense_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drone',
            old_name='fuel_capacity',
            new_name='capacity',
        ),
    ]
