# Generated by Django 5.1.4 on 2025-01-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exterminator', '0011_rename_fuel_capacity_drone_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='exterminatorlicense',
            name='business_registration_type',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='exterminatorlicense',
            name='license_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
