version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade pip
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "Cleaning up unnecessary files..."
      - find . -name "*.gz" -o -name "*.zip" -o -name "*.tar" -exec rm -rf {} \;
      - rm -rf .git .elasticbeanstalk __pycache__ node_modules

  build:
    commands:
      - echo "Running Django migrations and collectstatic..."
      - python manage.py migrate
      - python manage.py collectstatic --noinput

  post_build:
    commands:
      - echo "Removing any remaining unnecessary files..."
      - find . -name "*.gz" -o -name "*.zip" -exec rm -rf {} \;
      - echo "Application prepared for deployment."

artifacts:
  files:
    - '**/*'
  discard-paths: no
