# Generated by Django 4.2.14 on 2024-10-04 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArableLandInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('pnu', models.CharField(default='', max_length=30)),
                ('lndpclAr', models.CharField(default='', max_length=50)),
                ('cd', models.CharField(default='', max_length=8)),
                ('landNickName', models.CharField(default='', max_length=50)),
                ('cropsInfo', models.CharField(default='', max_length=50)),
                ('additionalPhoneNum', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_address', to='common.address')),
            ],
        ),
    ]
