# Generated by Django 4.2.14 on 2025-01-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roadaddress', models.CharField(blank=True, default='', max_length=50)),
                ('jibunAddress', models.CharField(default='', max_length=50)),
                ('detailAddress', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
