# Generated by Django 4.2.14 on 2024-10-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='roadaddress',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
