# Generated by Django 5.1.5 on 2025-02-02 14:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('bank_name', models.CharField(default='', max_length=50)),
                ('account_number', models.CharField(default='', max_length=50)),
                ('account_type', models.CharField(default='', max_length=50)),
                ('account_created', models.DateTimeField(auto_now_add=True)),
                ('account_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dealmothod', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'personal')], default=0)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(blank=True, default=None, null=True)),
                ('pesticide', models.CharField(blank=True, default='', max_length=50)),
                ('extraDetails', models.CharField(blank=True, default='', max_length=50)),
                ('setAveragePrice', models.IntegerField(default=0)),
                ('requestAmount', models.PositiveIntegerField(default=0)),
                ('reservateDepositAmount', models.PositiveIntegerField(default=1000)),
                ('checkState', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'done')], default=0)),
                ('requestDepositState', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'success'), (2, 'cancel')], default=0)),
                ('requestCancelTransactionKey', models.CharField(blank=True, default='', max_length=80)),
                ('exterminateState', models.PositiveSmallIntegerField(choices=[(0, 'matching'), (1, 'preparing'), (2, 'exterminating'), (3, 'done')], default=0)),
                ('reservateDepositState', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'success'), (2, 'cancel')], default=0)),
                ('depositCancelTransactionKey', models.CharField(blank=True, default='', max_length=80)),
                ('calculation', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'success'), (2, 'cancel')], default=0)),
            ],
        ),
    ]
