# Generated by Django 4.2.14 on 2025-01-13 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '__first__'),
        ('farmer', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exterminateState', models.PositiveSmallIntegerField(choices=[(0, 'matching'), (1, 'preparing'), (2, 'exterminating'), (3, 'done')], default=0)),
                ('checkState', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'done')], default=0)),
                ('calculation', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'success'), (2, 'cancel')], default=0)),
                ('dealmothod', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'personal')], default=0)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('pesticide', models.CharField(blank=True, default='', max_length=50)),
                ('setAveragePrice', models.IntegerField(default=0)),
                ('requestAmount', models.PositiveIntegerField(default=0)),
                ('requestDepositState', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'success'), (2, 'cancel')], default=0)),
                ('requestCancelTransactionKey', models.CharField(blank=True, default='', max_length=80)),
                ('reservateDepositAmount', models.PositiveIntegerField(default=1000)),
                ('reservateDepositState', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'success'), (2, 'cancel')], default=0)),
                ('depositCancelTransactionKey', models.CharField(blank=True, default='', max_length=80)),
                ('exterminator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_exterminator', to=settings.AUTH_USER_MODEL)),
                ('landInfo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_landInfo', to='farmer.farminfo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_owner', to=settings.AUTH_USER_MODEL)),
                ('requestTosspayments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_tosspayments', to='payments.tosspayments')),
                ('reservateTosspayments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservate_tosspayments', to='payments.tosspayments')),
            ],
        ),
    ]
