# Generated by Django 5.1.5 on 2025-01-31 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='accountCreated',
            new_name='account_created',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='accountNumber',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='accountType',
            new_name='account_type',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='accountUpdated',
            new_name='account_updated',
        ),
        migrations.RenameField(
            model_name='bankaccount',
            old_name='bankName',
            new_name='bank_name',
        ),
    ]
