# Generated by Django 5.1.5 on 2025-01-31 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(default='', max_length=50)),
                ('accountNumber', models.CharField(default='', max_length=50)),
                ('accountType', models.CharField(default='', max_length=50)),
                ('accountCreated', models.DateTimeField(auto_now_add=True)),
                ('accountUpdated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
