# Generated by Django 4.2.14 on 2025-02-01 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_rename_accountcreated_bankaccount_account_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='extraDetails',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='request',
            name='endDate',
            field=models.DateField(blank=True, default=''),
        ),
    ]
