# Generated by Django 4.2.14 on 2025-02-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_request_extradetails_alter_request_enddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='endDate',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
