# Generated by Django 5.1.5 on 2025-01-30 21:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(editable=False, max_length=16)),
                ('birthdate', models.CharField(editable=False, max_length=8)),
                ('gender', models.CharField(choices=[('0', 'Woman'), ('1', 'Man')], editable=False, max_length=1)),
                ('nationalinfo', models.CharField(choices=[('0', 'Domestic'), ('1', 'Foreigner')], editable=False, max_length=1)),
                ('mobileno', models.CharField(max_length=14, unique=True)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Drone Exterminator'), (4, 'Customer')], default=4)),
                ('road', models.CharField(blank=True, default='', max_length=50)),
                ('jibun', models.CharField(default='', max_length=50)),
                ('detail', models.CharField(default='', max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
