# Generated by Django 5.1.5 on 2025-01-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='sent_agreement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sent_agreement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
