# Generated by Django 4.2.14 on 2025-01-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('0', 'Woman'), ('1', 'Man')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nationalinfo',
            field=models.CharField(choices=[('0', 'Domestic'), ('1', 'Foreigner')], max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Drone Exterminator'), (4, 'Customer')], default=4),
        ),
        migrations.DeleteModel(
            name='Exterminator',
        ),
    ]
