# Generated by Django 5.1.5 on 2025-02-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='required_consent_date',
            field=models.DateTimeField(default=None),
        ),
    ]
