# Generated by Django 5.1.5 on 2025-02-06 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='sent_agreement',
            new_name='marketing_agreement',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='sent_agreement_date',
            new_name='marketing_agreement_date',
        ),
    ]
