# Generated by Django 5.1.4 on 2025-01-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="birthdate",
            field=models.CharField(editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("0", "Woman"), ("1", "Man")], editable=False, max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="name",
            field=models.CharField(editable=False, max_length=16),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="nationalinfo",
            field=models.CharField(
                choices=[("0", "Domestic"), ("1", "Foreigner")],
                editable=False,
                max_length=1,
            ),
        ),
    ]
