# Generated by Django 5.1.5 on 2025-02-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_sent_agreement_customuser_marketing_agreement_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='marketing_agreement',
            new_name='optinal_consent',
        ),
        migrations.AddField(
            model_name='customuser',
            name='required_consent_data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
