# Generated by Django 5.1.5 on 2025-02-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_required_consent_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='marketing_agreement_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
