# Generated by Django 5.1.5 on 2025-02-06 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_marketing_agreement_customuser_optinal_consent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='required_consent_data',
            new_name='required_consent_date',
        ),
    ]
