# Generated by Django 5.1.5 on 2025-02-09 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userchurnreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchurnreason',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='churn_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
