# Generated by Django 5.1.5 on 2025-02-10 21:08

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_userchurnreason_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='marketing_agreement_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='required_consent_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 21, 8, 58, 882332)),
        ),
        migrations.AlterField(
            model_name='userchurnreason',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='churn_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
