# Generated by Django 5.1.5 on 2025-02-10 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_customuser_marketing_agreement_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='required_consent_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 10, 21, 9, 7, 146146)),
        ),
    ]
