# Generated by Django 4.2.14 on 2024-10-04 21:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('exterminateState', models.PositiveSmallIntegerField(choices=[(0, 'matching'), (1, 'preparing'), (2, 'exterminating'), (3, 'done')], default=0)),
                ('customerCheckState', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'done')], default=0)),
                ('calculation', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'success'), (2, 'cancel')], default=0)),
                ('dealmothod', models.PositiveSmallIntegerField(choices=[(0, 'normal'), (1, 'personal')], default=0)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('pesticide', models.CharField(blank=True, default='', max_length=50)),
                ('setAveragePrice', models.IntegerField(default=0)),
                ('requestAmount', models.PositiveIntegerField(default=0)),
                ('requestDepositState', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'success'), (2, 'cancel')], default=0)),
                ('requestCancelTransactionKey', models.CharField(blank=True, default='', max_length=80)),
                ('reservateDepositAmount', models.PositiveIntegerField(default=1000)),
                ('reservateDepositState', models.PositiveSmallIntegerField(choices=[(0, 'checking'), (1, 'success'), (2, 'cancel')], default=0)),
                ('depositCancelTransactionKey', models.CharField(blank=True, default='', max_length=80)),
            ],
        ),
    ]
