# Generated by Django 4.2.14 on 2024-10-04 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farmrequest', '0001_initial'),
        ('customer', '0002_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='exterminatorinfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_exterminator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='landInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_landInfo', to='customer.arablelandinfo'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='request_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='requestTosspayments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='request_tosspayments', to='common.tosspayments'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='reservateTosspayments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservate_tosspayments', to='common.tosspayments'),
        ),
    ]
